// ─── CreateTradeRequest ───────────────────────────────────────────────────────
// For SELL offers (user buys): sellerPaymentAccountId is required,
//   buyerWalletId + buyerPublicAddress should be provided.
// For BUY offers (user sells): buyerPaymentAccountId is optional,
//   no wallet fields needed (deposit address auto-generated by backend).

class CreateTradeRequest {
  final String offerId;
  final double amount;
  final String? sellerPaymentAccountId; // Required for SELL offers
  final String? buyerPaymentAccountId; // Optional; recommended for BUY offers
  final String? buyerWalletId;
  final String? buyerPublicAddress;
  final String idempotencyKey;
  final String? note;

  const CreateTradeRequest({
    required this.offerId,
    required this.amount,
    this.sellerPaymentAccountId,
    this.buyerPaymentAccountId,
    this.buyerWalletId,
    this.buyerPublicAddress,
    required this.idempotencyKey,
    this.note,
  });

  Map<String, dynamic> toJson() => {
    'offerId': offerId.trim(),
    'amount': amount,
    'idempotencyKey': idempotencyKey.trim(),
    if (sellerPaymentAccountId != null &&
        sellerPaymentAccountId!.trim().isNotEmpty)
      'sellerPaymentAccountId': sellerPaymentAccountId!.trim(),
    if (buyerPaymentAccountId != null &&
        buyerPaymentAccountId!.trim().isNotEmpty)
      'buyerPaymentAccountId': buyerPaymentAccountId!.trim(),
    if (buyerWalletId != null && buyerWalletId!.trim().isNotEmpty)
      'buyerWalletId': buyerWalletId!.trim(),
    if (buyerPublicAddress != null && buyerPublicAddress!.trim().isNotEmpty)
      'buyerPublicAddress': buyerPublicAddress!.trim(),
    if (note != null && note!.trim().isNotEmpty) 'note': note!.trim(),
  };
}

// ─── TradesQuery ──────────────────────────────────────────────────────────────

class TradesQuery {
  final String? status;
  final String? offerId;
  final String? q;
  final int? page;
  final int? limit;

  const TradesQuery({this.status, this.offerId, this.q, this.page, this.limit});

  Map<String, String> toQueryMap() => {
    if (status != null && status!.trim().isNotEmpty) 'status': status!.trim(),
    if (offerId != null && offerId!.trim().isNotEmpty)
      'offerId': offerId!.trim(),
    if (q != null && q!.trim().isNotEmpty) 'q': q!.trim(),
    if (page != null && page! > 0) 'page': page!.toString(),
    if (limit != null && limit! > 0) 'limit': limit!.toString(),
  };
}

// ─── vF1 Action DTOs ──────────────────────────────────────────────────────────

/// SELL: user marks fiat as sent.
/// POST /trades/:id/actions/fiat-sent
class FiatSentRequest {
  final String? note;
  const FiatSentRequest({this.note});

  Map<String, dynamic> toJson() => {
    if (note != null && note!.trim().isNotEmpty) 'note': note!.trim(),
  };
}

/// SELL: merchant confirms fiat received.
/// POST /trades/:id/actions/fiat-received
class FiatReceivedRequest {
  const FiatReceivedRequest();
  Map<String, dynamic> toJson() => {};
}

/// BUY: merchant marks fiat as sent to user.
/// POST /trades/:id/actions/fiat-sent-merchant
class FiatSentMerchantRequest {
  final String? note;
  const FiatSentMerchantRequest({this.note});

  Map<String, dynamic> toJson() => {
    if (note != null && note!.trim().isNotEmpty) 'note': note!.trim(),
  };
}

/// BUY: user confirms fiat received from merchant.
/// POST /trades/:id/actions/confirm-received
class ConfirmReceivedRequest {
  const ConfirmReceivedRequest();
  Map<String, dynamic> toJson() => {};
}

/// Either party cancels the trade.
/// POST /trades/:id/actions/cancel
class CancelTradeActionRequest {
  final String? reason;
  const CancelTradeActionRequest({this.reason});

  Map<String, dynamic> toJson() => {
    if (reason != null && reason!.trim().isNotEmpty) 'reason': reason!.trim(),
  };
}

/// Either party opens a dispute.
/// POST /trades/:id/actions/open-dispute
class OpenDisputeActionRequest {
  final String reason;
  const OpenDisputeActionRequest({required this.reason});

  Map<String, dynamic> toJson() => {'reason': reason.trim()};
}

/// Send a message in the trade chat.
/// POST /trades/:id/chat/messages
class SendTradeChatRequest {
  final String message;
  const SendTradeChatRequest({required this.message});

  Map<String, dynamic> toJson() => {'message': message.trim()};
}

// ─── Legacy DTOs (kept for backward compat) ──────────────────────────────────

class CancelTradeRequest {
  final String idempotencyKey;
  final String? txHash;
  final String? reason;

  const CancelTradeRequest({
    required this.idempotencyKey,
    this.txHash,
    this.reason,
  });

  Map<String, dynamic> toJson() => {
    'idempotencyKey': idempotencyKey.trim(),
    if (txHash != null && txHash!.trim().isNotEmpty) 'txHash': txHash!.trim(),
    if (reason != null && reason!.trim().isNotEmpty) 'reason': reason!.trim(),
  };
}

class MarkPaidTradeRequest {
  final String idempotencyKey;

  const MarkPaidTradeRequest({required this.idempotencyKey});

  Map<String, dynamic> toJson() => {'idempotencyKey': idempotencyKey.trim()};
}

class ReleaseTradeRequest {
  final String idempotencyKey;
  final String? txHash;

  const ReleaseTradeRequest({required this.idempotencyKey, this.txHash});

  Map<String, dynamic> toJson() => {
    'idempotencyKey': idempotencyKey.trim(),
    if (txHash != null && txHash!.trim().isNotEmpty) 'txHash': txHash!.trim(),
  };
}

class SendTradeMessageRequest {
  final String message;

  const SendTradeMessageRequest({required this.message});

  Map<String, dynamic> toJson() => {'message': message.trim()};
}
